@startuml component-popup-logic
component [PopupLogic] {
  [listWorkspaces()]
  [addWorkspace()]
  [workspaceClicked()]
  [workspaceSettingsClicked()]
  [tabRemoved()]
  [tabUpdated()]
}

component [Workspace] {
  [name]
  [windowId]
  [getTabs()]
}

component [WorkspaceStorage] {
  [values()]
}

component [PopupActions] {
  [openWorkspace()]
}

component [Utils] {
  [interpolateTemplate()]
}

component [WORKSPACE_TEMPLATE]

PopupLogic --> Workspace : uses
PopupLogic --> WorkspaceStorage : uses
PopupLogic --> PopupActions : uses
PopupLogic --> Utils : uses
PopupLogic --> WORKSPACE_TEMPLATE : uses
@enduml